### ISSUE TITLE
配置完成后启动时报错

### ISSUE THREAD

**Issue by moemeow233** [Byaidu/QChatBot-GPT#10]
一切都安装配置完成之后，执行python3 chatbot.py后一直提示“2022-12-12 03:51:17.097 | INFO     | graia.ariadne.connection.ws:_:89 - Websocket connection closed
2022-12-12 03:51:17.098 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
2022-12-12 03:51:22.099 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...”

https://pastebin.com/wm7z7we7
mirai-api-http的配置如下：
https://pastebin.com/yBFvHwzG

**Comment by Byaidu** [comment]
请参考 https://graiax.cn/before/install_mirai.html 来配置 setting.yaml，否则预设的连接密钥对不上

```
adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: GraiaxVerifyKey
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: [*]
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
```

**Comment by moemeow233** [comment]
> 请参考 https://graiax.cn/before/install_mirai.html 来配置 setting.yaml，否则预设的连接密钥对不上
> 
> ```
> adapters:
>   - http
>   - ws
> debug: false
> enableVerify: true
> verifyKey: GraiaxVerifyKey
> singleMode: false
> cacheSize: 4096
> adapterSettings:
>   http:
>     host: localhost
>     port: 8080
>     cors: [*]
>   ws:
>     host: localhost
>     port: 8080
>     reservedSyncId: -1
> ```

已解决，感谢
