### ISSUE TITLE
请问使用的creart包是哪个

### ISSUE THREAD

**Issue by cincinno** [Byaidu/QChatBot-GPT#12]
Traceback (most recent call last):
  File "chatbot.py", line 10, in <module>
    from creart import create
ModuleNotFoundError: No module named 'creart'

尝试了pip install，但是并没有找到creart包

**Comment by Byaidu** [comment]
graia-ariadne

**Comment by cincinno** [comment]
> graia-ariadne

换了台电脑解决了，谢谢
