### ISSUE TITLE
请问一下这个报错是为什么，网上的方法都试了也不行

### ISSUE THREAD

**Issue by lazybainuo** [Byaidu/QChatBot-GPT#7]
DEBUG:asyncio:Using proactor: IocpProactor
Traceback (most recent call last):
  File "H:\bot3\chatbot.py", line 45, in <module>
    app = Ariadne(connection=config(int(os.getenv("169734874")),"GraiaxVerifyKey"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by lazybainuo** [comment]
环境是python3.9.2

**Comment by Byaidu** [comment]
请正确设置环境变量，而不是替换代码中的字符串

**Comment by lazybainuo** [comment]
> 请正确设置环境变量，而不是替换代码中的字符串

已经改好了，可以正常运行了，没仔细看，看成了直接填上去（

**Comment by lazybainuo** [comment]
> 请正确设置环境变量，而不是替换代码中的字符串

谢谢
