### ISSUE TITLE
为什么我的代码会有这样的错误，环境变量什么的都弄好了

### ISSUE THREAD

**Issue by FKZ-rainbow** [Byaidu/QChatBot-GPT#8]

**Comment by FKZ-rainbow** [comment]
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
DEBUG:asyncio:Using proactor: IocpProactor
Traceback (most recent call last):
  File "D:/qqchet/silicon-master/chatbot.py", line 43, in <module>
    app = Ariadne(connection=config(int(os.getenv("BOT_ACCOUNT")),"GraiaxVerifyKey"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Byaidu** [comment]
环境变量 BOT_ACCOUNT 没配置好，导致 os.getenv("BOT_ACCOUNT") 结果为 None，所以会报错
